---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sci-viz-deployment
  labels:
    app: sci-viz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sci-viz
  template:
    metadata:
      labels:
        app: sci-viz
    spec:
      containers:
      - name: sci-viz
        image: jverswijver/sci-viz:0.2.0-prerelease-7
        env:
          - name: CHOKIDAR_USEPOLLING
            value: "true"
          - name: REACT_APP_DJSCIVIZ_BACKEND_PREFIX
            value: "/api"
          - name: DJSCIVIZ_SPEC_PATH
            value: "/main/specs/sci-viz-config.yaml"
        command: ["/bin/sh"]
        args: ["-c","sh sci-viz-hotreload-dev.sh"]
        ports:
        - containerPort: 80
        volumeMounts:
          - name: spec
            mountPath: "/main/specs"
            readOnly: true
          - name: logo
            mountPath: "/main/src/media/ibl_logo.png"
            readOnly: true
            subPath: "ibl_logo.png"
          - name: brainbow
            mountPath: "/main/src/media/home_ibl_brainbow.jpg"
            readOnly: true
            subPath: "home_ibl_brainbow.jpg"
          - name: media-md
            mountPath: "/main/public/media/"
            readOnly: true
          - name: icon
            mountPath: "/main/public/ibl_icon.png"
            readOnly: true
            subPath: "ibl_icon.png"
      volumes:
      - name: spec
        configMap:
          name: sci-viz-config
      - name: logo
        configMap:
          name: logo
      - name: brainbow
        configMap:
          name: brainbow
      - name: media-md
        configMap:
          name: media-md
      - name: icon
        configMap:
          name: icon
...

